### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Invalid index

### ISSUE THREAD

**Issue by mesqueeb** [ethereumjs/ethereumjs-wallet#70]
I get this error:
```
AssertionError [ERR_ASSERTION]: Invalid index
    at /Users/x/.ghq/github.com/DRI-network/swingby/contract/node_modules/hdkey/lib/hdkey.js:87:5
    at Array.forEach (<anonymous>)
    at HDKey.derive (/Users/lucaban/.ghq/github.com/DRI-network/swingby/contract/node_modules/hdkey/lib/hdkey.js:79:11)
    at EthereumHDKey.derivePath (/Users/x/.ghq/github.com/DRI-network/swingby/contract/node_modules/ethereumjs-wallet/hdkey.js:37:32)
```

**Comment by mesqueeb** [comment]
It was because of a mistaken path in `hdwallet.derivePath(path)`

**Comment by holgerd77** [comment]
Ok, thanks for updating and closing.

**Comment by gasparyanyur** [comment]
I have the same error. 

`hdwallet.derivePath("m/44'/0'/0/1")` return  an error look loke this
`AssertionError [ERR_ASSERTION]: Could not derive hardened child key`.
